---
title: "Relatório Estatística Computacional"
author: 
- Cristian Pessatti dos Anjos
- Thor Marinho
- Rafael Alisson Schipiura
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
header-includes: 
  - \renewcommand{\and}{\\}
---

```{r, echo = FALSE, include = FALSE}
library("tidyverse")
library("magrittr")

worms <- read_csv2("./worms.csv")
worms %<>% mutate(across(where(is.character), factor))
legenda <- read_csv2("./legenda.csv")
rownames(legenda) <- legenda$var
```

# Análise Univariada
```{r, echo = FALSE, include = TRUE}
numeric_vars <- colnames(worms %>% select_if(is.numeric))
for (aplot in numeric_vars) {
	symplot <- ensym(aplot)
	n <- worms %>% select(all_of(symplot)) %>% drop_na(all_of(symplot)) %>% nrow()
	sturges <- log(n,2)+1
	print(worms %>% drop_na(all_of(symplot)) %>% ggplot(aes(x = !!symplot)) + geom_histogram(bins = sturges) +  labs(x = legenda[aplot,][2], y="frequência"))
}
factor_vars <- colnames(worms %>% select_if(is.factor))
for (aplot in factor_vars) {
	symplot <- ensym(aplot)
	print(worms %>% drop_na(all_of(symplot)) %>% ggplot(aes(x = !!symplot)) + geom_bar() + theme(axis.text.x = element_text(angle = 90)) + labs(x = legenda[aplot,][2], y = "frequência"))
}
```

# Análise Bivariada

```{r, echo = FALSE, include = TRUE}
duas_numeric <- combn(numeric_vars, 2)
for (aplot in 1:ncol(duas_numeric)) {
	primeira <- duas_numeric[,aplot][1]
	segunda <- duas_numeric[,aplot][2]
	symprim <- sym(primeira)
	symseg <- sym(segunda)
	print(worms %>% drop_na(all_of(symprim), all_of(symseg)) %>% ggplot(aes(x = !!symprim, y = !!symseg)) + geom_point() + geom_smooth(method = "lm",formula = y ~ x) + labs(x = legenda[primeira,][2], y = legenda[segunda,][2]) )
}
duas_factor <- combn(factor_vars, 2)
for (aplot in 1:ncol(duas_factor)) {
	primeira <- duas_factor[,aplot][1]
	symprim <- sym(primeira)
	segunda <- duas_factor[,aplot][2]
	symseg <- sym(segunda)
	print(worms %>% drop_na(all_of(symprim), all_of(symseg)) %>% ggplot(aes(x = !!symprim, y = !!symseg)) + geom_count() + labs(x = legenda[primeira,][2], y = legenda[segunda,][2]))
}
duas_mista <- expand_grid(factor_vars, numeric_vars)
for (aplot in 1:nrow(duas_mista)) {
	primeira <- duas_mista[aplot,][[1]]
	symprim <- sym(primeira)
	segunda <- duas_mista[aplot,][[2]]
	symseg <- sym(segunda)
	print(worms %>% drop_na(all_of(symprim), all_of(symseg)) %>% ggplot(aes(x = !!symprim, y = !!symseg)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90)) + labs(x = legenda[primeira,][2], y = legenda[segunda,][2]))
}
```

# Tabela de Correlação

```{r, echo = FALSE, include = TRUE}
library(corrplot)

worms_numeric <- worms[, numeric_vars]

mycor<- function(x, ...){
  r<- apply(x, 2, function(j){
    apply(x, 2, function(i){
      as.numeric(cor.test(i,j, ...)$estimate)
    })
  })
  P<- apply(x, 2, function(j){
    apply(x, 2, function(i){
      as.numeric(cor.test(i,j, ...)$p.value)
    })
  })
  out<-c()
  out$P<- P
  out$r<- r
  return(out)
}

mycorDat <- mycor(worms_numeric)

jpeg("corplotTest.jpg", width=800, height=800, quality=100, pointsize=24)
corrplot(corr=mycorDat$r,
        p.mat = mycorDat$P,
        type="full", insig="pch", sig.level =.1, pch.cex = .9)
dev.off()
```
# Correlação das variáveis com a variável densidade
```{r, echo = FALSE, include = TRUE}
nomes_colunas_dens_corr <- c("Estatística", "Parâmetro", "p-valor", "Estimativa", "Valor nulo", "Alternativa", "Método", "Variável", "Intervalo de confiança")

dens_corr <- matrix(ncol = 9)
for(numeric_var in numeric_vars) {
  corr_result <- cor.test(worms_numeric$dens, worms_numeric[[numeric_var]])
  corr_result$data.name <- numeric_var
  dens_corr <- rbind(
    matrix(corr_result, ncol = 9),
    dens_corr
  )
}

dens_corr_df <- data.frame(dens_corr)
colnames(dens_corr_df) <- nomes_colunas_dens_corr
knitr::kable(dens_corr_df)
```

# Correlação das variáveis com a variável massa
```{r, echo = FALSE, include = TRUE}
nomes_colunas_massa_corr <- c("Estatística", "Parâmetro", "p-valor", "Estimativa", "Valor nulo", "Alternativa", "Método", "Variável", "Intervalo de confiança")

massa_corr <- matrix(ncol = 9)
for(numeric_var in numeric_vars) {
  corr_result <- cor.test(worms_numeric$massa, worms_numeric[[numeric_var]])
  corr_result$data.name <- numeric_var
  massa_corr <- rbind(
    matrix(corr_result, ncol = 9),
    massa_corr
  )
}

massa_corr_df <- data.frame(massa_corr)
colnames(massa_corr_df) <- nomes_colunas_massa_corr
knitr::kable(massa_corr_df)
```

# Teste de hipótese para verificar linearidade da variável em relação a variável dens
```{r, echo = FALSE, include = TRUE}
check_hypothesis <- function(variable, alpha_value, df, t_statistic) {
  p.upper <- pt(abs(t), df = df, lower.tail = FALSE)
  p.lower <- pt(-abs(t), df = df, lower.tail = TRUE)
  p <- p.upper + p.lower
  return(p <= alpha)
}

hypothesis_result_dens_corr_df <- data.frame(`Variável` = character(), `Rejeita hipótese nula` = logical())

for (var in dens_corr_df$`Variável`) {
  df <- dens_corr_df[dens_corr_df$`Variável` == var,]$`Parâmetro`[[1]] - 2
  hypothesis_result_dens_corr <- check_hypothesis(variable = var, alpha_value = 0.05, df = df, t_statistic = dens_corr_df$`Estatística`)
  hypothesis_result_dens_corr_df[nrow(hypothesis_result_dens_corr_df) + 1,] <- c(var, hypothesis_result_dens_corr)
}

knitr::kable(hypothesis_result_dens_corr_df)
```

# Teste de hipótese para verificar linearidade da variável em relação a variável massa
```{r, echo = FALSE, include = TRUE}
hypothesis_result_massa_corr_df <- data.frame(`Variável` = character(), `Rejeita hipótese nula` = logical())

for (var in massa_corr_df$`Variável`) {
  df <- massa_corr_df[massa_corr_df$`Variável` == var,]$`Parâmetro`[[1]] - 2
  hypothesis_result_massa_corr <- check_hypothesis(variable = var, alpha_value = 0.05, df = df, t_statistic = massa_corr_df$`Estatística`)
  hypothesis_result_massa_corr_df[nrow(hypothesis_result_massa_corr_df) + 1,] <- c(var, hypothesis_result_massa_corr)
}

knitr::kable(hypothesis_result_massa_corr_df)
```